version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ditiss     
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
 
    volumes:
      - "./:/docker-entrypoint-initdb.d"
    networks:
      - lms
  www:
    depends_on:
      - db
    image: php:8.1.1-apache
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lms
  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment: 
      - PMA_HOST = db
      - PMA_PORT = 3306    
    networks:
      - lms

networks:
  lms:
    driver: bridge
